name: Tweet Every 4 Hours

on:
  workflow_dispatch:  # Allows manual trigger via GitHub Actions
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours at 00 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository content
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install Python dependencies
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure requirements.txt is in the repo

      # Step 4: Print environment variables for debugging
      - name: Print environment variables (for debugging)
        run: |
          echo "CONSUMER_KEY=${{ secrets.CONSUMER_KEY }}"
          echo "CONSUMER_SECRET=${{ secrets.CONSUMER_SECRET }}"
          echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}"
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}"

      # Step 5: Execute Python script (main.py)
      - name: Execute Python script (main.py)
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python main.py

      # Step 6: Verify cron is working correctly (for debugging purposes)
      - name: Verify Cron Trigger Time
        run: |
          echo "Current UTC Time: $(date -u)"
